"use client";

import Papa from "papaparse";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { userSchema } from "@/lib/validations/user.schema";

interface CsvUser {
  full_name: string;
  email: string;
  role: "admin" | "judge" | "participant" | "mentor";
  team_name?: string;
}

export function BulkUserUpload() {
  const [rows, setRows] = useState<CsvUser[]>([]);

  function parse(file: File) {
    Papa.parse<CsvUser>(file, {
      header: true,
      complete: (result) => {
        const valid = result.data.filter((row) => userSchema.safeParse(row).success);
        setRows(valid);
        toast.success(`${valid.length} trainers parsed`);
      },
    });
  }

  return (
    <div className="grid gap-3">
      <input className="min-h-12 rounded-md border border-border bg-slate-950/40 p-3" type="file" accept=".csv" onChange={(event) => event.target.files?.[0] && parse(event.target.files[0])} />
      <Button disabled={!rows.length} onClick={() => toast.info("Connect Supabase admin auth to invite parsed trainers.")}>Bulk Create {rows.length ? `${rows.length} Trainers` : "Trainers"}</Button>
      <p className="text-sm text-slate-300">CSV: full_name, email, role, team_name. Trainer IDs, QR tokens, passwords, and sprites are generated by admin creation utilities.</p>
    </div>
  );
}
